version: "3.9"

networks:
  nexus-public:
    driver: overlay
    attachable: true

  nexus-internal:
    driver: overlay
    attachable: true

services:

  backend:
    image: ${BACKEND_IMAGE}

    networks:
      - nexus-public
      - nexus-internal

    environment:
      PORT: "3000"
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: ${MONGO_URI}

    ports:
      - "3000:3000"

    deploy:
      replicas: 2

      placement:
        constraints:
          - node.labels.backend == true

      restart_policy:
        condition: on-failure

      update_config:
        parallelism: 1
        delay: 10s