name: Deploy Stack File

on:
  push:
    branches:
      - main
    paths:
      - stack.yml
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy stack.yml to EC2 Manager
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_SSH_HOST }}
          username: ${{ secrets.AWS_SSH_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "stack.yml"
          target: "/home/${{ secrets.AWS_SSH_USER }}/todo-app/"

      - name: Execute Swarm Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_SSH_HOST }}
          username: ${{ secrets.AWS_SSH_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.AWS_SSH_USER }}/todo-app/
            cd /home/${{ secrets.AWS_SSH_USER }}/todo-app/
            docker stack deploy -c stack.yml todo_app --with-registry-auth